DELIMITER $$
CREATE DEFINER=`root`@`localhost` FUNCTION `CHECKTC`(TC VARCHAR(250)) RETURNS tinyint(4)
BEGIN
    DECLARE RESULT TINYINT;
    DECLARE D1    TINYINT;
    DECLARE D2    TINYINT;
    DECLARE D3    TINYINT;
    DECLARE D4    TINYINT;
    DECLARE D5    TINYINT;
    DECLARE D6    TINYINT;
    DECLARE D7    TINYINT;
    DECLARE D8    TINYINT;
    DECLARE D9    TINYINT;
    DECLARE D10   TINYINT;
    DECLARE D11   TINYINT;
    DECLARE CD1    INT;
    DECLARE CD2    INT;
    DECLARE TCKN BIGINT;
    
    SET TCKN = CONVERT(TC, SIGNED);
      
   IF LENGTH(TC) <> 11 THEN
      SET RESULT = 0;
   ELSE
   	SET D1 = (TCKN DIV POWER(10, 10)) % 10;
	SET D2 = (TCKN DIV POWER(10, 9)) % 10;
	SET D3 = (TCKN DIV POWER(10, 8)) % 10;
	SET D4 = (TCKN DIV POWER(10, 7)) % 10;
	SET D5 = (TCKN DIV POWER(10, 6)) % 10;
	SET D6 = (TCKN DIV POWER(10, 5)) % 10;
	SET D7 = (TCKN DIV POWER(10, 4)) % 10;
	SET D8 = (TCKN DIV POWER(10, 3)) % 10;
	SET D9 = (TCKN DIV POWER(10, 2)) % 10;
	SET D10 = (TCKN DIV POWER(10, 1)) % 10; 
	SET D11 = (TCKN DIV POWER(10, 0)) % 10;
	
    SET CD1 = (((D1+D3+D5+D7+D9)*7)-(D2+D4+D6+D8))%10;
	SET CD2 = (D1+D2+D3+D4+D5+D6+D7+D8+D9+CD1)%10;
	
	IF D10=CD1 AND D11=CD2 THEN
		SET RESULT = 1;
	ELSE 
		SET RESULT = 0;
    END IF;

   END IF;
   RETURN RESULT;
END$$
DELIMITER ;